# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version
python: 3.6

# Install the pip dependencies
install:
  - make init
  - make install
  - pip install codecov coveralls

# Run the unit test
script:
  - make test
  #- make docs
  #- coverage run tests.py

after_success:
  - codecov
  - coveralls

# Push the results back to codecov
#after_success:
#- codecov

deploy:
  provider: pypi
  username: "__token__"
  password: $PYPI_TOKEN
  #distributions: "sdist bdist_wheel"
  on:
    tags: true